#!/bin/sh

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

print_help(){
  echo "Usage:    tradelog [-h|--help]"
  echo "          tradelog [FILTER] [COMMAND] [LOG [LOG2 [...]]"
  echo "                   "
  echo "Commands: list-tick"
  echo "          profit"
  echo "          pos"
  echo "          last-price"
  echo "          hist-ord"
  echo "          graph-pos"
  echo "                     "
  echo "Filters:  -a DATETIME"
  echo "          -b DATETIME"
  echo "          -t TICKER"
  echo "          -w WIDTH"
}

COMMAND=""
WIDTH=""
TICKER=""
DATETIME_A="0000-00-00 00:00:00"
DATETIME_B="9999-99-99 99:99:99"
LOGFILES=""
LOGFILES_GZ=""
INPUT=""
FILTER_INPUT=""
DATE_FILTER=""
TICKER_FILTER=""
OUTPUT=""


while [ "$#" -gt 0 ]
do
  case "$1" in
  -h | --help)
    print_help
    exit 0
    ;;
  list-tick | profit | pos | last-price | hist-ord | graph-pos)
    COMMAND="$1"
    shift
    ;;
  -w)
    if [ "$WIDTH" == "" ];then
      WIDTH="$2"
      shift
      shift
    else
      exit 1
    fi
    ;;
  -a)
    DATETIME_A="$2"
    shift
    shift
    ;;
  -b)
    DATETIME_B="$2"
    shift
    shift
    ;;
  -t)
    TICKER="$2|$TICKER"
    shift
    shift
    ;;
  *.gz)
    LOGFILES_GZ="$1 $LOGFILES_GZ"
    shift
    ;;
  *.log)
    LOGFILES="$1 $LOGFILES"
    shift
    ;;
  esac
done

if [ "$LOGFILES_GZ" != "" ];then
  INPUT="$(gzip -d -c $LOGFILES_GZ | cat $LOGFILES - | sort)"
fi
if [ "$LOGFILES" != "" ]; then
  INPUT=$(cat $LOGFILES)
else
  INPUT=$(cat)
fi

FILTER_INPUT=$(echo "$INPUT" | awk -v time_a="$DATETIME_A" -v time_b="$DATETIME_B" -F ';' '{if ($1 > time_a && $1 < time_b) {print $0}}')
if [ "$TICKER" != "" ];then
  FILTER_INPUT=$(echo "$FILTER_INPUT" | awk -v tck="$TICKER" 'BEGIN = split(tck, tick)}
  {for(i=1; i<=x;i++) if(tick[i] == $2) {print $0}}')
fi
case "$COMMAND" in
  list-tick)
  OUTPUT=$(echo "$FILTER_INPUT" | awk -F ';' '{print $2}' | sort -u)
    ;;
  profit)
    ;;
  pos)
    ;;
  last-price)
    ;;
  hist-ord)
    ;;
  graph-pos)
    ;;
  *)
  OUTPUT="$FILTER_INPUT"
    ;;
esac

echo "$OUTPUT"
