#!/bin/sh

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

print_help(){
  echo "Usage:    tradelog [-h|--help]"
  echo "          tradelog [FILTER] [COMMAND] [LOG [LOG2 [...]]"
  echo "                   "
  echo "Commands: list-tick"
  echo "          profit"
  echo "          pos"
  echo "          last-price"
  echo "          hist-ord"
  echo "          graph-pos"
  echo "                     "
  echo "Filters:  -a DATETIME"
  echo "          -b DATETIME"
  echo "          -t TICKER"
  echo "          -w WIDTH"
}

COMMAND=""
WIDTH=""
TICKER=""
DATETIME_A="0000-00-00 00:00:00"
DATETIME_B="9999-99-99 99:99:99"
LOGFILES=""
LOGFILES_GZ=""
INPUT=""
FILTER_INPUT=""
OUTPUT=""
TICKER_LIST=""

while [ "$#" -gt 0 ]
do
  case "$1" in
  -h | --help)
    print_help
    exit 0
    ;;
  list-tick | profit | pos | last-price | hist-ord | graph-pos)
    COMMAND="$1"
    shift
    ;;
  -w)
    if [ "$WIDTH" != "" ];then
      exit 1
    else
      WIDTH="$2"
      shift
      shift
    fi
    ;;
  -a)
    DATETIME_A="$2"
    shift
    shift
    ;;
  -b)
    DATETIME_B="$2"
    shift
    shift
    ;;
  -t)
    TICKER="$2;$TICKER"
    shift
    shift
    ;;
  *.gz)
    LOGFILES_GZ="$1 $LOGFILES_GZ"
    shift
    ;;
  *.log)
    LOGFILES="$1 $LOGFILES"
    shift
    ;;
  *)
    exit 1
    ;;
  esac
done

if [ "$LOGFILES_GZ" != "" ];then
  INPUT="$(gzip -d -c $LOGFILES_GZ | cat $LOGFILES - | sort)"
else
  if [ "$LOGFILES" != "" ]; then
    INPUT=$(cat $LOGFILES)
  else
    INPUT=$(cat)
  fi
fi
FILTER_INPUT=$(echo "$INPUT" | awk -v aft="$DATETIME_A" -v bfr="$DATETIME_B" -F ';' '{if ($1 > aft && $1 < bfr) {print $0}}')
if [ "$TICKER" != "" ];then
  FILTER_INPUT=$(echo "$FILTER_INPUT" | awk -v tck="$TICKER" -F ';' 'BEGIN {x = split(tck, tick)}
  {for(i=1; i<=x;i++) if(tick[i] == $2) {print $0}}')
fi
case "$COMMAND" in
  list-tick)
  OUTPUT=$(echo "$FILTER_INPUT" | awk -F ';' '{print $2}' | sort -u)
    ;;
  profit)
  OUTPUT=$(echo "$FILTER_INPUT" | awk -F ';' '{if($3 == "buy"){num -= $4 * $6}if($3 == "sell"){num += $4 * $6}} END {printf("%.2f",num)}')
    ;;
  pos)
  OUTPUT=$(echo "$FILTER_INPUT" | awk -F ';' '{if($3 == "buy"){ticks[$2] += $6}if($3 == "sell"){ticks[$2] -= $6}if($1 > lastdate[$2]){lastdate[$2] = $1; lastprice[$2]=$4}}END{ for (tick in ticks){num=sprintf("%.2f",ticks[tick]*lastprice[tick]); printf("%9-s : %s\n",tick,num)} }' | sort -r -t':' -nk2)
    ;;
  last-price)
  OUTPUT=$(echo "$FILTER_INPUT" | awk -F ';' '{if($1 > lastdate[$2]){lastdate[$2] = $1; lastprices[$2]=$4}}END{ for (lastprice in lastprices){printf("%9-s : %s\n",lastprice,lastprices[lastprice])} }' | sort)
    ;;
  hist-ord)
    OUTPUT=$(echo "$FILTER_INPUT" | awk -F ';' -v wd="$WIDTH" '{ticks[$2]+=1; if(ticks[$2]>maxcount){maxcount=ticks[$2]}}END{x=1;if(wd != ""){x=maxcount/wd}for(tick in ticks){printf("%9-s :",tick);for(i=x;i<=ticks[tick];i+=x){printf("#")}printf("\n");}}' | sort)
    ;;
  graph-pos)
  OUTPUT=$(echo "$FILTER_INPUT" | awk -F ';' -v wd="$WIDTH" 'function abs(x){return((x<0.0) ? -x : x)}{if($3 == "buy"){ticks[$2] += $6}if($3 == "sell"){ticks[$2] -= $6}if($1 > lastdate[$2]){lastdate[$2] = $1; lastprice[$2]=$4}}END{ for (tick in ticks){price[tick]=ticks[tick]*lastprice[tick]; if(int(abs(price[tick])) > maxprice){maxprice=int(abs(price[tick]))} x=1000; if(wd != ""){x=maxprice/wd}for(tick in ticks){printf("%9-s :",tick);if(price[tick]<0){for(i=-x;i>=price[tick];i-=x){printf("!")}}if(price[tick]>0){for(i=x;i<=price[tick];i+=x){printf("#")}}printf("\n");}}' | sort)
    ;;
  *)
  OUTPUT="$FILTER_INPUT"
    ;;
esac

echo "$OUTPUT"
